name: CI Workshop
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - maingit 

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the C# code
      run: dotnet build

    - name: Run C# tests
      run: dotnet test

    - name: Run Typescript dependencies
      working-directory: ./DotnetTemplate.Web
      run: npm ci

    - name: Run Typescript build
      working-directory: ./DotnetTemplate.Web
      run: npm run build

    - name: Run the linter TypeScript
      working-directory: ./DotnetTemplate.Web
      run: npm run lint

    - name: Run the TypeScript tests
      working-directory: ./DotnetTemplate.Web
      run: npm t